server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 541224

logging:
  level:
    cn.jhmarryme: debug
  file:
    name: ./var/log/test.log