server:
  port: 7777

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://1.14.140.53:3306/monolithic-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: jh541224

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl