server:
  port: 8060
spring:
  application:
    name: imooc-secutity
  profiles:
    active: dev
imooc:
  security:
    code:
      image:
        length: 2
        width: 600
        url: /authentication/form
      smsCode:
        url: /authentication/mobile
#    browser:
#      loginType: REDIRECT
#      loginPage: /demo-login.html