spring:
  datasource:
    url: jdbc:mysql://120.78.171.38:3306/imooc-security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: jh541224
    driver-class-name: com.mysql.jdbc.Driver
  #    暂时关闭session配置
  session:
    store-type: redis
  redis:
    host: 120.78.171.38
    port: 6379
#security:
#  basic:
#    enabled: false
swagger:
  enable: true