server:
  port: 8060
spring:
  application:
    name: imooc-secutity
  profiles:
    active: dev
imooc:
  security:
    code:
      image:
        length: 6
        width: 200
        url: /user,/user/*
#    browser:
#      loginType: REDIRECT
#      loginPage: /demo-login.html