server:
  port: 8060
spring:
  application:
    name: imooc-secutity
  profiles:
    active: dev
imooc:
  security:
    code:
      image:
        length: 2
        width: 200
        url: /authentication/form
#    browser:
#      loginType: REDIRECT
#      loginPage: /demo-login.html