server:
  port: 8060
spring:
  application:
    name: imooc-secutity
  profiles:
    active: dev
imooc:
  security:
    code:
      image:
        length: 1
        width: 600
        url: /authentication/form
      smsCode:
        url: /authentication/mobile
    social:
      qq:
        appId: 101386962
        appSecret: 2a0f820407df400b84a854d054be8b6a
        providerId: qq
#    browser:
#      loginType: REDIRECT
#      loginPage: /demo-login.html