server:
  port: 8060
spring:
  application:
    name: imooc-secutity
  profiles:
    active: dev
imooc:
  security:
    code:
      image:
        length: 1
        width: 600
        url: /authentication/form
      smsCode:
        url: /authentication/mobile
    social:
      qq:
        appId: 101930634
        appSecret: 8bd77811f967d28560b53e60bce2bb2d
    browser:
      signUpUrl: /demo-signUp.html
#      loginType: REDIRECT
#      loginPage: /demo-login.html