server:
  port: 8060
#控制session的超时时间，单位：s，默认是30分钟，即30分钟内不做任何操作就会认为超时，然后清除session里的用户信息，最短为1分钟
  session:
    timeout: 60
spring:
  application:
    name: imooc-secutity
  profiles:
    active: dev
imooc:
  security:
    code:
      image:
        length: 2
        width: 600
        url: /authentication/form
      smsCode:
        url: /authentication/mobile
    social:
      qq:
        appId: 101930634
        appSecret: 8bd77811f967d28560b53e60bce2bb2d
    browser:
      signUpUrl: /demo-signUp.html
#      loginType: REDIRECT
#      loginPage: /demo-login.html